hosts:
  - host: service1
    servers:
      - port: 5000
        ip: 10.0.0.5
        weight: 1
  - host: service2
    servers:
      - port: 5000
        ip: 10.0.0.6
        weight: 1
  - host: service3
    servers:
      - port: 5000
        ip: 10.0.0.7
        weight: 1

  - host: extra
    servers:
      - port: 5000
        ip: 0.0.0.0
        weight: 1
 

  


  