hosts:
  - host: service1
    servers:
      - port: 5000
        ip: 10.0.0.5
        weight: 1
      - port: 5000
        ip: 10.0.0.6
        weight: 2

  - host: extra
    servers:
      - port: 5000
        ip: 0.0.0.0
        weight: 1
 

  


  