hosts:
  - host: service1
    servers:
      - port: 5000
        ip: 10.0.0.5
        weight: 1
      - port: 5000
        ip: 10.0.0.6
        weight: 2
      - port: 5000
        ip: 10.0.0.7
        weight: 3
  - host: service2
    servers:
      - port: 5000
        ip: 10.0.0.5
        weight: 1
      - port: 5000
        ip: 10.0.0.6
        weight: 2
  - host: service3
    servers:
      - port: 5000
        ip: 10.0.0.5
        weight: 1

  


  